//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesiSuTup
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayıtAlanı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KayıtAlanı()
        {
            this.SiparisBilgi = new HashSet<SiparisBilgi>();
        }
    
        public int musteriID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Şifre { get; set; }
        public string AdSoyad { get; set; }
        public string Eposta { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<int> YoneticiMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisBilgi> SiparisBilgi { get; set; }
    }
}
