//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesiSuTup
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisBilgi
    {
        public int SiparisID { get; set; }
        public string KullaniciAdı { get; set; }
        public string AdSoyad { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public string TelNo { get; set; }
        public string Eposta { get; set; }
        public string KucukSu { get; set; }
        public string OrtaSu { get; set; }
        public string BuyukSu { get; set; }
        public string KucukTup { get; set; }
        public string SismanTup { get; set; }
        public string UzunTup { get; set; }
        public string SiparisTutari { get; set; }
        public string Adres { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual KayıtAlanı KayıtAlanı { get; set; }
    }
}
